config/routes.rb
NewBlog::Application.routes.draw do

  get "users/new"

  root to: 'new_blog#home'

  match '/signup', to: 'users#new'
  match '/login', to: 'new_blog#login'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/new_blog_controller.rb
class NewBlogController < ApplicationController
  def home
  end

  def login
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_blog_helper.rb
module NewBlogHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Very Very logo", root_path , id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Blog",    '#' %></li>
              <li><%= link_to "Login",    login_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog project | <%= yield(:title) %> </title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      
    </div>
  </body>
</html>

app/views/new_blog/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Home</h1>

  <h3>
	Content
  </h3>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/new_blog/login.html.erb
<h1>Blog#login</h1>
<p>Find me in app/views/blog/login.html.erb</p>

app/views/new_blog/signup.html.erb
<h1>Blog#signup</h1>
<p>Find me in app/views/blog/signup.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>